//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 12:56:18 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zis.rs/xml/schemes/action", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.uns.ac.rs.xml.util.actions;
